FROM alpine:latest

# RUN apt-get -y update

# RUN apt-get -y dist-upgrade

# RUN DEBIAN_FRONTEND="noninteractive" apt-get -y install tzdata

# RUN apt-get install -y apache2

# RUN apt-get install -y php-curl php-gd php-mbstring php-xml php-xmlrpc php-soap php-intl php-zip libapache2-mod-php  php-mysql

# RUN apt-get install -y mysql-server

# RUN apt-get install -y curl unzip expect

RUN apk add apache2 php7-curl php7-gd php7-mbstring php7-xml php7-xmlrpc php7-soap php7-intl php7-zip php7-apache2 mysql-client mysql curl unzip expect

# RUN a2enmod rewrite

# RUN apache2ctl configtest

RUN curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"; unzip awscliv2.zip; ./aws/install; rm -rvf aws/ awscliv2.zip

COPY mysql_secure_installation_auto.sh /data/mysql_secure_installation_auto.sh

# RUN rm /var/www/html/*

COPY entry.sh /data/entry.sh

RUN chmod +x /data/*.sh

ENTRYPOINT [ "apache2" ]

EXPOSE 80